[workspace]
resolver = "3"
members = [
    "services/*",
]

[workspace.dependencies]
tokio = { version = "1.50", features = ["full"] }
axum = "0.8"
# tonic = "0.10"
serde = { version = "1.0", features = ["derive"] }
# tracing = "0.1"
diesel = { version = "2.2.0", features = ["postgres", "chrono"] }
diesel_migrations = "2.2.0"
pq-sys = { version = "0.7.5", features = ["bundled"] }
chrono = { version = "0.4.45", features = ["serde"] }
