services:
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PSW}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USR} -d ${POSTGRES_USR}"]
      interval: 5s
      timeout: 5s
      retries: 5
  gateway:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
      tags:
        - gsaplus-api:gateway
    environment:
      DATABASE_URL: postgres://${POSTGRES_USR}:${POSTGRES_PSW}@postgres/${POSTGRES_USR}
    ports:
      - 3001:3000
